package com.syb.product.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BStoreBillRecord implements Serializable {
    private Integer bsbId;

    private String bsbAccountNo;

    private String bsbBillNo;

    private BigDecimal bsbAmount;

    private Byte bsbOrderType;

    private Byte bsbType;

    private String bsbTradingAccount;

    private String bsbTradeRecordNo;

    private Byte bsbTransactionType;

    private String bsbMerchantNo;

    private String bsbTradeName;

    private Boolean bsbStatus;

    private String bsbDescr;

    private Date bsbCreateTime;

    private Date bsbUpdateTime;

    private BigDecimal bsbNeedServiceFee;

    private BigDecimal bsbAccountBalance;

    private Byte bsbReview;

    private String bsbWithdrawApplyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_id
     *
     * @return the value of b_store_bill_record.bsb_id
     *
     * @mbggenerated
     */
    public Integer getBsbId() {
        return bsbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_id
     *
     * @param bsbId the value for b_store_bill_record.bsb_id
     *
     * @mbggenerated
     */
    public void setBsbId(Integer bsbId) {
        this.bsbId = bsbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_account_no
     *
     * @return the value of b_store_bill_record.bsb_account_no
     *
     * @mbggenerated
     */
    public String getBsbAccountNo() {
        return bsbAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_account_no
     *
     * @param bsbAccountNo the value for b_store_bill_record.bsb_account_no
     *
     * @mbggenerated
     */
    public void setBsbAccountNo(String bsbAccountNo) {
        this.bsbAccountNo = bsbAccountNo == null ? null : bsbAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_bill_no
     *
     * @return the value of b_store_bill_record.bsb_bill_no
     *
     * @mbggenerated
     */
    public String getBsbBillNo() {
        return bsbBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_bill_no
     *
     * @param bsbBillNo the value for b_store_bill_record.bsb_bill_no
     *
     * @mbggenerated
     */
    public void setBsbBillNo(String bsbBillNo) {
        this.bsbBillNo = bsbBillNo == null ? null : bsbBillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_amount
     *
     * @return the value of b_store_bill_record.bsb_amount
     *
     * @mbggenerated
     */
    public BigDecimal getBsbAmount() {
        return bsbAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_amount
     *
     * @param bsbAmount the value for b_store_bill_record.bsb_amount
     *
     * @mbggenerated
     */
    public void setBsbAmount(BigDecimal bsbAmount) {
        this.bsbAmount = bsbAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_order_type
     *
     * @return the value of b_store_bill_record.bsb_order_type
     *
     * @mbggenerated
     */
    public Byte getBsbOrderType() {
        return bsbOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_order_type
     *
     * @param bsbOrderType the value for b_store_bill_record.bsb_order_type
     *
     * @mbggenerated
     */
    public void setBsbOrderType(Byte bsbOrderType) {
        this.bsbOrderType = bsbOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_type
     *
     * @return the value of b_store_bill_record.bsb_type
     *
     * @mbggenerated
     */
    public Byte getBsbType() {
        return bsbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_type
     *
     * @param bsbType the value for b_store_bill_record.bsb_type
     *
     * @mbggenerated
     */
    public void setBsbType(Byte bsbType) {
        this.bsbType = bsbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_trading_account
     *
     * @return the value of b_store_bill_record.bsb_trading_account
     *
     * @mbggenerated
     */
    public String getBsbTradingAccount() {
        return bsbTradingAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_trading_account
     *
     * @param bsbTradingAccount the value for b_store_bill_record.bsb_trading_account
     *
     * @mbggenerated
     */
    public void setBsbTradingAccount(String bsbTradingAccount) {
        this.bsbTradingAccount = bsbTradingAccount == null ? null : bsbTradingAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_trade_record_no
     *
     * @return the value of b_store_bill_record.bsb_trade_record_no
     *
     * @mbggenerated
     */
    public String getBsbTradeRecordNo() {
        return bsbTradeRecordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_trade_record_no
     *
     * @param bsbTradeRecordNo the value for b_store_bill_record.bsb_trade_record_no
     *
     * @mbggenerated
     */
    public void setBsbTradeRecordNo(String bsbTradeRecordNo) {
        this.bsbTradeRecordNo = bsbTradeRecordNo == null ? null : bsbTradeRecordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_transaction_type
     *
     * @return the value of b_store_bill_record.bsb_transaction_type
     *
     * @mbggenerated
     */
    public Byte getBsbTransactionType() {
        return bsbTransactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_transaction_type
     *
     * @param bsbTransactionType the value for b_store_bill_record.bsb_transaction_type
     *
     * @mbggenerated
     */
    public void setBsbTransactionType(Byte bsbTransactionType) {
        this.bsbTransactionType = bsbTransactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_merchant_no
     *
     * @return the value of b_store_bill_record.bsb_merchant_no
     *
     * @mbggenerated
     */
    public String getBsbMerchantNo() {
        return bsbMerchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_merchant_no
     *
     * @param bsbMerchantNo the value for b_store_bill_record.bsb_merchant_no
     *
     * @mbggenerated
     */
    public void setBsbMerchantNo(String bsbMerchantNo) {
        this.bsbMerchantNo = bsbMerchantNo == null ? null : bsbMerchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_trade_name
     *
     * @return the value of b_store_bill_record.bsb_trade_name
     *
     * @mbggenerated
     */
    public String getBsbTradeName() {
        return bsbTradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_trade_name
     *
     * @param bsbTradeName the value for b_store_bill_record.bsb_trade_name
     *
     * @mbggenerated
     */
    public void setBsbTradeName(String bsbTradeName) {
        this.bsbTradeName = bsbTradeName == null ? null : bsbTradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_status
     *
     * @return the value of b_store_bill_record.bsb_status
     *
     * @mbggenerated
     */
    public Boolean getBsbStatus() {
        return bsbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_status
     *
     * @param bsbStatus the value for b_store_bill_record.bsb_status
     *
     * @mbggenerated
     */
    public void setBsbStatus(Boolean bsbStatus) {
        this.bsbStatus = bsbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_descr
     *
     * @return the value of b_store_bill_record.bsb_descr
     *
     * @mbggenerated
     */
    public String getBsbDescr() {
        return bsbDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_descr
     *
     * @param bsbDescr the value for b_store_bill_record.bsb_descr
     *
     * @mbggenerated
     */
    public void setBsbDescr(String bsbDescr) {
        this.bsbDescr = bsbDescr == null ? null : bsbDescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_create_time
     *
     * @return the value of b_store_bill_record.bsb_create_time
     *
     * @mbggenerated
     */
    public Date getBsbCreateTime() {
        return bsbCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_create_time
     *
     * @param bsbCreateTime the value for b_store_bill_record.bsb_create_time
     *
     * @mbggenerated
     */
    public void setBsbCreateTime(Date bsbCreateTime) {
        this.bsbCreateTime = bsbCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_update_time
     *
     * @return the value of b_store_bill_record.bsb_update_time
     *
     * @mbggenerated
     */
    public Date getBsbUpdateTime() {
        return bsbUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_update_time
     *
     * @param bsbUpdateTime the value for b_store_bill_record.bsb_update_time
     *
     * @mbggenerated
     */
    public void setBsbUpdateTime(Date bsbUpdateTime) {
        this.bsbUpdateTime = bsbUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_need_service_fee
     *
     * @return the value of b_store_bill_record.bsb_need_service_fee
     *
     * @mbggenerated
     */
    public BigDecimal getBsbNeedServiceFee() {
        return bsbNeedServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_need_service_fee
     *
     * @param bsbNeedServiceFee the value for b_store_bill_record.bsb_need_service_fee
     *
     * @mbggenerated
     */
    public void setBsbNeedServiceFee(BigDecimal bsbNeedServiceFee) {
        this.bsbNeedServiceFee = bsbNeedServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_account_balance
     *
     * @return the value of b_store_bill_record.bsb_account_balance
     *
     * @mbggenerated
     */
    public BigDecimal getBsbAccountBalance() {
        return bsbAccountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_account_balance
     *
     * @param bsbAccountBalance the value for b_store_bill_record.bsb_account_balance
     *
     * @mbggenerated
     */
    public void setBsbAccountBalance(BigDecimal bsbAccountBalance) {
        this.bsbAccountBalance = bsbAccountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_review
     *
     * @return the value of b_store_bill_record.bsb_review
     *
     * @mbggenerated
     */
    public Byte getBsbReview() {
        return bsbReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_review
     *
     * @param bsbReview the value for b_store_bill_record.bsb_review
     *
     * @mbggenerated
     */
    public void setBsbReview(Byte bsbReview) {
        this.bsbReview = bsbReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_store_bill_record.bsb_withdraw_apply_no
     *
     * @return the value of b_store_bill_record.bsb_withdraw_apply_no
     *
     * @mbggenerated
     */
    public String getBsbWithdrawApplyNo() {
        return bsbWithdrawApplyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_store_bill_record.bsb_withdraw_apply_no
     *
     * @param bsbWithdrawApplyNo the value for b_store_bill_record.bsb_withdraw_apply_no
     *
     * @mbggenerated
     */
    public void setBsbWithdrawApplyNo(String bsbWithdrawApplyNo) {
        this.bsbWithdrawApplyNo = bsbWithdrawApplyNo == null ? null : bsbWithdrawApplyNo.trim();
    }
}