package com.syb.product.model;

import com.syb.common.generator.pagination.Page;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BStoreBillRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public BStoreBillRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setPage(Page page) {
        this.page = page;
    }

    public Page getPage() {
        return this.page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBsbIdIsNull() {
            addCriterion("bsb_id is null");
            return (Criteria) this;
        }

        public Criteria andBsbIdIsNotNull() {
            addCriterion("bsb_id is not null");
            return (Criteria) this;
        }

        public Criteria andBsbIdEqualTo(Integer value) {
            addCriterion("bsb_id =", value, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdNotEqualTo(Integer value) {
            addCriterion("bsb_id <>", value, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdGreaterThan(Integer value) {
            addCriterion("bsb_id >", value, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bsb_id >=", value, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdLessThan(Integer value) {
            addCriterion("bsb_id <", value, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdLessThanOrEqualTo(Integer value) {
            addCriterion("bsb_id <=", value, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdIn(List<Integer> values) {
            addCriterion("bsb_id in", values, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdNotIn(List<Integer> values) {
            addCriterion("bsb_id not in", values, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdBetween(Integer value1, Integer value2) {
            addCriterion("bsb_id between", value1, value2, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bsb_id not between", value1, value2, "bsbId");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoIsNull() {
            addCriterion("bsb_account_no is null");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoIsNotNull() {
            addCriterion("bsb_account_no is not null");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoEqualTo(String value) {
            addCriterion("bsb_account_no =", value, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoNotEqualTo(String value) {
            addCriterion("bsb_account_no <>", value, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoGreaterThan(String value) {
            addCriterion("bsb_account_no >", value, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_account_no >=", value, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoLessThan(String value) {
            addCriterion("bsb_account_no <", value, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoLessThanOrEqualTo(String value) {
            addCriterion("bsb_account_no <=", value, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoLike(String value) {
            addCriterion("bsb_account_no like", value, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoNotLike(String value) {
            addCriterion("bsb_account_no not like", value, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoIn(List<String> values) {
            addCriterion("bsb_account_no in", values, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoNotIn(List<String> values) {
            addCriterion("bsb_account_no not in", values, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoBetween(String value1, String value2) {
            addCriterion("bsb_account_no between", value1, value2, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbAccountNoNotBetween(String value1, String value2) {
            addCriterion("bsb_account_no not between", value1, value2, "bsbAccountNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoIsNull() {
            addCriterion("bsb_bill_no is null");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoIsNotNull() {
            addCriterion("bsb_bill_no is not null");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoEqualTo(String value) {
            addCriterion("bsb_bill_no =", value, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoNotEqualTo(String value) {
            addCriterion("bsb_bill_no <>", value, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoGreaterThan(String value) {
            addCriterion("bsb_bill_no >", value, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_bill_no >=", value, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoLessThan(String value) {
            addCriterion("bsb_bill_no <", value, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoLessThanOrEqualTo(String value) {
            addCriterion("bsb_bill_no <=", value, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoLike(String value) {
            addCriterion("bsb_bill_no like", value, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoNotLike(String value) {
            addCriterion("bsb_bill_no not like", value, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoIn(List<String> values) {
            addCriterion("bsb_bill_no in", values, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoNotIn(List<String> values) {
            addCriterion("bsb_bill_no not in", values, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoBetween(String value1, String value2) {
            addCriterion("bsb_bill_no between", value1, value2, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbBillNoNotBetween(String value1, String value2) {
            addCriterion("bsb_bill_no not between", value1, value2, "bsbBillNo");
            return (Criteria) this;
        }

        public Criteria andBsbAmountIsNull() {
            addCriterion("bsb_amount is null");
            return (Criteria) this;
        }

        public Criteria andBsbAmountIsNotNull() {
            addCriterion("bsb_amount is not null");
            return (Criteria) this;
        }

        public Criteria andBsbAmountEqualTo(BigDecimal value) {
            addCriterion("bsb_amount =", value, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountNotEqualTo(BigDecimal value) {
            addCriterion("bsb_amount <>", value, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountGreaterThan(BigDecimal value) {
            addCriterion("bsb_amount >", value, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bsb_amount >=", value, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountLessThan(BigDecimal value) {
            addCriterion("bsb_amount <", value, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bsb_amount <=", value, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountIn(List<BigDecimal> values) {
            addCriterion("bsb_amount in", values, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountNotIn(List<BigDecimal> values) {
            addCriterion("bsb_amount not in", values, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bsb_amount between", value1, value2, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bsb_amount not between", value1, value2, "bsbAmount");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeIsNull() {
            addCriterion("bsb_order_type is null");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeIsNotNull() {
            addCriterion("bsb_order_type is not null");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeEqualTo(Byte value) {
            addCriterion("bsb_order_type =", value, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeNotEqualTo(Byte value) {
            addCriterion("bsb_order_type <>", value, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeGreaterThan(Byte value) {
            addCriterion("bsb_order_type >", value, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("bsb_order_type >=", value, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeLessThan(Byte value) {
            addCriterion("bsb_order_type <", value, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeLessThanOrEqualTo(Byte value) {
            addCriterion("bsb_order_type <=", value, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeIn(List<Byte> values) {
            addCriterion("bsb_order_type in", values, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeNotIn(List<Byte> values) {
            addCriterion("bsb_order_type not in", values, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeBetween(Byte value1, Byte value2) {
            addCriterion("bsb_order_type between", value1, value2, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbOrderTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("bsb_order_type not between", value1, value2, "bsbOrderType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeIsNull() {
            addCriterion("bsb_type is null");
            return (Criteria) this;
        }

        public Criteria andBsbTypeIsNotNull() {
            addCriterion("bsb_type is not null");
            return (Criteria) this;
        }

        public Criteria andBsbTypeEqualTo(Byte value) {
            addCriterion("bsb_type =", value, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeNotEqualTo(Byte value) {
            addCriterion("bsb_type <>", value, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeGreaterThan(Byte value) {
            addCriterion("bsb_type >", value, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("bsb_type >=", value, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeLessThan(Byte value) {
            addCriterion("bsb_type <", value, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeLessThanOrEqualTo(Byte value) {
            addCriterion("bsb_type <=", value, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeIn(List<Byte> values) {
            addCriterion("bsb_type in", values, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeNotIn(List<Byte> values) {
            addCriterion("bsb_type not in", values, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeBetween(Byte value1, Byte value2) {
            addCriterion("bsb_type between", value1, value2, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("bsb_type not between", value1, value2, "bsbType");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountIsNull() {
            addCriterion("bsb_trading_account is null");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountIsNotNull() {
            addCriterion("bsb_trading_account is not null");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountEqualTo(String value) {
            addCriterion("bsb_trading_account =", value, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountNotEqualTo(String value) {
            addCriterion("bsb_trading_account <>", value, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountGreaterThan(String value) {
            addCriterion("bsb_trading_account >", value, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_trading_account >=", value, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountLessThan(String value) {
            addCriterion("bsb_trading_account <", value, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountLessThanOrEqualTo(String value) {
            addCriterion("bsb_trading_account <=", value, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountLike(String value) {
            addCriterion("bsb_trading_account like", value, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountNotLike(String value) {
            addCriterion("bsb_trading_account not like", value, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountIn(List<String> values) {
            addCriterion("bsb_trading_account in", values, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountNotIn(List<String> values) {
            addCriterion("bsb_trading_account not in", values, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountBetween(String value1, String value2) {
            addCriterion("bsb_trading_account between", value1, value2, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradingAccountNotBetween(String value1, String value2) {
            addCriterion("bsb_trading_account not between", value1, value2, "bsbTradingAccount");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoIsNull() {
            addCriterion("bsb_trade_record_no is null");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoIsNotNull() {
            addCriterion("bsb_trade_record_no is not null");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoEqualTo(String value) {
            addCriterion("bsb_trade_record_no =", value, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoNotEqualTo(String value) {
            addCriterion("bsb_trade_record_no <>", value, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoGreaterThan(String value) {
            addCriterion("bsb_trade_record_no >", value, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_trade_record_no >=", value, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoLessThan(String value) {
            addCriterion("bsb_trade_record_no <", value, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoLessThanOrEqualTo(String value) {
            addCriterion("bsb_trade_record_no <=", value, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoLike(String value) {
            addCriterion("bsb_trade_record_no like", value, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoNotLike(String value) {
            addCriterion("bsb_trade_record_no not like", value, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoIn(List<String> values) {
            addCriterion("bsb_trade_record_no in", values, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoNotIn(List<String> values) {
            addCriterion("bsb_trade_record_no not in", values, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoBetween(String value1, String value2) {
            addCriterion("bsb_trade_record_no between", value1, value2, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeRecordNoNotBetween(String value1, String value2) {
            addCriterion("bsb_trade_record_no not between", value1, value2, "bsbTradeRecordNo");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeIsNull() {
            addCriterion("bsb_transaction_type is null");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeIsNotNull() {
            addCriterion("bsb_transaction_type is not null");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeEqualTo(Byte value) {
            addCriterion("bsb_transaction_type =", value, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeNotEqualTo(Byte value) {
            addCriterion("bsb_transaction_type <>", value, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeGreaterThan(Byte value) {
            addCriterion("bsb_transaction_type >", value, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("bsb_transaction_type >=", value, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeLessThan(Byte value) {
            addCriterion("bsb_transaction_type <", value, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeLessThanOrEqualTo(Byte value) {
            addCriterion("bsb_transaction_type <=", value, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeIn(List<Byte> values) {
            addCriterion("bsb_transaction_type in", values, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeNotIn(List<Byte> values) {
            addCriterion("bsb_transaction_type not in", values, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeBetween(Byte value1, Byte value2) {
            addCriterion("bsb_transaction_type between", value1, value2, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbTransactionTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("bsb_transaction_type not between", value1, value2, "bsbTransactionType");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoIsNull() {
            addCriterion("bsb_merchant_no is null");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoIsNotNull() {
            addCriterion("bsb_merchant_no is not null");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoEqualTo(String value) {
            addCriterion("bsb_merchant_no =", value, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoNotEqualTo(String value) {
            addCriterion("bsb_merchant_no <>", value, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoGreaterThan(String value) {
            addCriterion("bsb_merchant_no >", value, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_merchant_no >=", value, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoLessThan(String value) {
            addCriterion("bsb_merchant_no <", value, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoLessThanOrEqualTo(String value) {
            addCriterion("bsb_merchant_no <=", value, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoLike(String value) {
            addCriterion("bsb_merchant_no like", value, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoNotLike(String value) {
            addCriterion("bsb_merchant_no not like", value, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoIn(List<String> values) {
            addCriterion("bsb_merchant_no in", values, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoNotIn(List<String> values) {
            addCriterion("bsb_merchant_no not in", values, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoBetween(String value1, String value2) {
            addCriterion("bsb_merchant_no between", value1, value2, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbMerchantNoNotBetween(String value1, String value2) {
            addCriterion("bsb_merchant_no not between", value1, value2, "bsbMerchantNo");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameIsNull() {
            addCriterion("bsb_trade_name is null");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameIsNotNull() {
            addCriterion("bsb_trade_name is not null");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameEqualTo(String value) {
            addCriterion("bsb_trade_name =", value, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameNotEqualTo(String value) {
            addCriterion("bsb_trade_name <>", value, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameGreaterThan(String value) {
            addCriterion("bsb_trade_name >", value, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_trade_name >=", value, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameLessThan(String value) {
            addCriterion("bsb_trade_name <", value, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameLessThanOrEqualTo(String value) {
            addCriterion("bsb_trade_name <=", value, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameLike(String value) {
            addCriterion("bsb_trade_name like", value, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameNotLike(String value) {
            addCriterion("bsb_trade_name not like", value, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameIn(List<String> values) {
            addCriterion("bsb_trade_name in", values, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameNotIn(List<String> values) {
            addCriterion("bsb_trade_name not in", values, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameBetween(String value1, String value2) {
            addCriterion("bsb_trade_name between", value1, value2, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbTradeNameNotBetween(String value1, String value2) {
            addCriterion("bsb_trade_name not between", value1, value2, "bsbTradeName");
            return (Criteria) this;
        }

        public Criteria andBsbStatusIsNull() {
            addCriterion("bsb_status is null");
            return (Criteria) this;
        }

        public Criteria andBsbStatusIsNotNull() {
            addCriterion("bsb_status is not null");
            return (Criteria) this;
        }

        public Criteria andBsbStatusEqualTo(Boolean value) {
            addCriterion("bsb_status =", value, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusNotEqualTo(Boolean value) {
            addCriterion("bsb_status <>", value, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusGreaterThan(Boolean value) {
            addCriterion("bsb_status >", value, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("bsb_status >=", value, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusLessThan(Boolean value) {
            addCriterion("bsb_status <", value, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("bsb_status <=", value, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusIn(List<Boolean> values) {
            addCriterion("bsb_status in", values, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusNotIn(List<Boolean> values) {
            addCriterion("bsb_status not in", values, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("bsb_status between", value1, value2, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("bsb_status not between", value1, value2, "bsbStatus");
            return (Criteria) this;
        }

        public Criteria andBsbDescrIsNull() {
            addCriterion("bsb_descr is null");
            return (Criteria) this;
        }

        public Criteria andBsbDescrIsNotNull() {
            addCriterion("bsb_descr is not null");
            return (Criteria) this;
        }

        public Criteria andBsbDescrEqualTo(String value) {
            addCriterion("bsb_descr =", value, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrNotEqualTo(String value) {
            addCriterion("bsb_descr <>", value, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrGreaterThan(String value) {
            addCriterion("bsb_descr >", value, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_descr >=", value, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrLessThan(String value) {
            addCriterion("bsb_descr <", value, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrLessThanOrEqualTo(String value) {
            addCriterion("bsb_descr <=", value, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrLike(String value) {
            addCriterion("bsb_descr like", value, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrNotLike(String value) {
            addCriterion("bsb_descr not like", value, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrIn(List<String> values) {
            addCriterion("bsb_descr in", values, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrNotIn(List<String> values) {
            addCriterion("bsb_descr not in", values, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrBetween(String value1, String value2) {
            addCriterion("bsb_descr between", value1, value2, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbDescrNotBetween(String value1, String value2) {
            addCriterion("bsb_descr not between", value1, value2, "bsbDescr");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeIsNull() {
            addCriterion("bsb_create_time is null");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeIsNotNull() {
            addCriterion("bsb_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeEqualTo(Date value) {
            addCriterion("bsb_create_time =", value, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeNotEqualTo(Date value) {
            addCriterion("bsb_create_time <>", value, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeGreaterThan(Date value) {
            addCriterion("bsb_create_time >", value, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("bsb_create_time >=", value, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeLessThan(Date value) {
            addCriterion("bsb_create_time <", value, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("bsb_create_time <=", value, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeIn(List<Date> values) {
            addCriterion("bsb_create_time in", values, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeNotIn(List<Date> values) {
            addCriterion("bsb_create_time not in", values, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeBetween(Date value1, Date value2) {
            addCriterion("bsb_create_time between", value1, value2, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("bsb_create_time not between", value1, value2, "bsbCreateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeIsNull() {
            addCriterion("bsb_update_time is null");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeIsNotNull() {
            addCriterion("bsb_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeEqualTo(Date value) {
            addCriterion("bsb_update_time =", value, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeNotEqualTo(Date value) {
            addCriterion("bsb_update_time <>", value, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeGreaterThan(Date value) {
            addCriterion("bsb_update_time >", value, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("bsb_update_time >=", value, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeLessThan(Date value) {
            addCriterion("bsb_update_time <", value, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("bsb_update_time <=", value, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeIn(List<Date> values) {
            addCriterion("bsb_update_time in", values, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeNotIn(List<Date> values) {
            addCriterion("bsb_update_time not in", values, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("bsb_update_time between", value1, value2, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("bsb_update_time not between", value1, value2, "bsbUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeIsNull() {
            addCriterion("bsb_need_service_fee is null");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeIsNotNull() {
            addCriterion("bsb_need_service_fee is not null");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeEqualTo(BigDecimal value) {
            addCriterion("bsb_need_service_fee =", value, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeNotEqualTo(BigDecimal value) {
            addCriterion("bsb_need_service_fee <>", value, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeGreaterThan(BigDecimal value) {
            addCriterion("bsb_need_service_fee >", value, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bsb_need_service_fee >=", value, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeLessThan(BigDecimal value) {
            addCriterion("bsb_need_service_fee <", value, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bsb_need_service_fee <=", value, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeIn(List<BigDecimal> values) {
            addCriterion("bsb_need_service_fee in", values, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeNotIn(List<BigDecimal> values) {
            addCriterion("bsb_need_service_fee not in", values, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bsb_need_service_fee between", value1, value2, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbNeedServiceFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bsb_need_service_fee not between", value1, value2, "bsbNeedServiceFee");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceIsNull() {
            addCriterion("bsb_account_balance is null");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceIsNotNull() {
            addCriterion("bsb_account_balance is not null");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceEqualTo(BigDecimal value) {
            addCriterion("bsb_account_balance =", value, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceNotEqualTo(BigDecimal value) {
            addCriterion("bsb_account_balance <>", value, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceGreaterThan(BigDecimal value) {
            addCriterion("bsb_account_balance >", value, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bsb_account_balance >=", value, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceLessThan(BigDecimal value) {
            addCriterion("bsb_account_balance <", value, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bsb_account_balance <=", value, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceIn(List<BigDecimal> values) {
            addCriterion("bsb_account_balance in", values, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceNotIn(List<BigDecimal> values) {
            addCriterion("bsb_account_balance not in", values, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bsb_account_balance between", value1, value2, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbAccountBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bsb_account_balance not between", value1, value2, "bsbAccountBalance");
            return (Criteria) this;
        }

        public Criteria andBsbReviewIsNull() {
            addCriterion("bsb_review is null");
            return (Criteria) this;
        }

        public Criteria andBsbReviewIsNotNull() {
            addCriterion("bsb_review is not null");
            return (Criteria) this;
        }

        public Criteria andBsbReviewEqualTo(Byte value) {
            addCriterion("bsb_review =", value, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewNotEqualTo(Byte value) {
            addCriterion("bsb_review <>", value, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewGreaterThan(Byte value) {
            addCriterion("bsb_review >", value, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewGreaterThanOrEqualTo(Byte value) {
            addCriterion("bsb_review >=", value, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewLessThan(Byte value) {
            addCriterion("bsb_review <", value, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewLessThanOrEqualTo(Byte value) {
            addCriterion("bsb_review <=", value, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewIn(List<Byte> values) {
            addCriterion("bsb_review in", values, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewNotIn(List<Byte> values) {
            addCriterion("bsb_review not in", values, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewBetween(Byte value1, Byte value2) {
            addCriterion("bsb_review between", value1, value2, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbReviewNotBetween(Byte value1, Byte value2) {
            addCriterion("bsb_review not between", value1, value2, "bsbReview");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoIsNull() {
            addCriterion("bsb_withdraw_apply_no is null");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoIsNotNull() {
            addCriterion("bsb_withdraw_apply_no is not null");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoEqualTo(String value) {
            addCriterion("bsb_withdraw_apply_no =", value, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoNotEqualTo(String value) {
            addCriterion("bsb_withdraw_apply_no <>", value, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoGreaterThan(String value) {
            addCriterion("bsb_withdraw_apply_no >", value, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_withdraw_apply_no >=", value, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoLessThan(String value) {
            addCriterion("bsb_withdraw_apply_no <", value, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoLessThanOrEqualTo(String value) {
            addCriterion("bsb_withdraw_apply_no <=", value, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoLike(String value) {
            addCriterion("bsb_withdraw_apply_no like", value, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoNotLike(String value) {
            addCriterion("bsb_withdraw_apply_no not like", value, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoIn(List<String> values) {
            addCriterion("bsb_withdraw_apply_no in", values, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoNotIn(List<String> values) {
            addCriterion("bsb_withdraw_apply_no not in", values, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoBetween(String value1, String value2) {
            addCriterion("bsb_withdraw_apply_no between", value1, value2, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }

        public Criteria andBsbWithdrawApplyNoNotBetween(String value1, String value2) {
            addCriterion("bsb_withdraw_apply_no not between", value1, value2, "bsbWithdrawApplyNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_store_bill_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_store_bill_record
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}