CREATE TABLE`we_chat_pay_bills` (
	`id` INTEGER NOT NULL auto_increment,
	`appId` VARCHAR (32),
	`mchId` VARCHAR (32),
	`payTime` DATETIME,
	`subMchId` VARCHAR (32),
	`deviceInfo` VARCHAR (32),
	`transactionId` VARCHAR (64),
	`outTradeNo` VARCHAR (64),
	`userInfo` VARCHAR (64),
	`payType` VARCHAR (28),
	`refundType` VARCHAR (28),
	`bankType` VARCHAR (28),
	`cashFeeType` VARCHAR (28),
	`totalFee` DECIMAL (15, 2),
	`couponFee` DECIMAL (15, 2),
	`body` VARCHAR (500),
	`attach` VARCHAR (1024),
	`commission` VARCHAR (28),
	`commissionRate` VARCHAR (28),
	`status` VARCHAR (64),
	`validateStatus` INTEGER (2) default 0,
	`error` VARCHAR (500),
	`createdAt` DATETIME NOT NULL,
	`updatedAt` DATETIME NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE = INNODB;